### ISSUE TITLE
Support artist level copyrights 

### ISSUE THREAD

**Issue by vzell** [kellnerd/musicbrainz-bookmarklets#18]
Given the release https://musicbrainz.org/release/c17bcba4-a9d0-48b3-9d36-807a8d038f48/edit-relationships
I wanted to parse the artist level copyright information 

![image](https://user-images.githubusercontent.com/1648084/148686098-a93005f8-3fa9-4507-8a85-fa08dd3e3eef.png)

Is there a way to fall back on `artist` level copyright information after checking `label` level copyright info ?

Almost all Bruce Springsteen releases have `artist` level copyright information

**Comment by kellnerd** [comment]
Hmm, the simplest solution for the script would be to check if the name of the copyright holder matches the (release) artist name. In this case it could fill the dialog with an artist-release/recording relationship, in all other cases it would assume a label.
I think this should be sufficient, or have you ever seen an artist copyright which is not owned by the release artists themselves?

**Comment by vzell** [comment]
No ... never ... I think your suggestion is absolutely right

**Comment by kellnerd** [comment]
Support added in 228b435830081871197ed41c8808add13b702916, released as part of v2022.1.14.2.
