### ISSUE TITLE
"John J. Mellencamp" label wrongly "Credited as: John J"

### ISSUE THREAD

**Issue by vzell** [kellnerd/musicbrainz-bookmarklets#21]
Given the back scan at https://i.discogs.com/xcUK2GTKqWV14LwCuk6aXlACij8_7bOgCTP_Lw3X3nc/rs:fit/g:sm/q:90/h:466/w:600/czM6Ly9kaXNjb2dz/LWltYWdlcy9SLTIx/ODM0MDMxLTE2NDI4/MDI0ODUtODk2OS5q/cGVn.jpeg for release https://musicbrainz.org/release/ff1b1be9-9e3a-41c2-aecf-ba65c3516212 there is the following credit:

℗© 2021 John J. Mellencamp, under exclusive license to Republic Records, a division of UMG Recordings, Inc.

which fails at the "dot" as you can see in the following screenshot:

![image](https://user-images.githubusercontent.com/1648084/151040482-30ca1782-ac04-4d0f-b7ba-b5503b6caf61.png)

The label can be found here https://musicbrainz.org/label/0de712ce-8c53-48bb-962d-51c8351ca75e

**Comment by kellnerd** [comment]
Unfortunately there is no way for the parser to know which dots terminate a name and which are part of the name, you have to help it a little bit. Changing the credit terminator to `/$|(?=,|\sunder\s)/` will ignore the dot and should be enough in this case. If you don't want the script to permanently store this change, you have to undo the change after parsing.

See [Supported notice formats and relationship types](https://github.com/kellnerd/musicbrainz-bookmarklets/wiki/Parse-Copyright-Notices#supported-notice-formats-and-relationship-types) for more details.

**Comment by kellnerd** [comment]
Temporarily changing the credit terminator or the name separator has become easier with v2022.1.27 which added reset buttons for the pattern inputs.

**Comment by vzell** [comment]
thx .. works like a charm
