### ISSUE TITLE
Add MusicBrainz and bookmarklets topics to this GitHub repo

### ISSUE THREAD

**Issue by jesus2099** [kellnerd/musicbrainz-bookmarklets#5]
You can do that in the repo settings.
Maybe you can anticipate and also add userscripts, so that we can find it through this kind of tags: https://github.com/search?q=topic%3Amusicbrainz+topic%3Auserscripts

**Comment by kellnerd** [comment]
Thank you, I have now added the topics _musicbrainz_ and _bookmarklets_ and will keep this issue open as a reminder to add _userscripts_ once it is applicable.

**Comment by kellnerd** [comment]
I have now added *userscripts* to the tags since https://github.com/kellnerd/musicbrainz-bookmarklets/commit/e7dd428bb1973a7a2a740f0d95b12e6f11d5095b publishes the first version of the *Guess Unicode punctuation* userscript, so far only with support for the release editor.

**Comment by jesus2099** [comment]
Congratulations! ☺️
