### ISSUE TITLE
enhancement request: whitespace, bullets

### ISSUE THREAD

**Issue by rtyle** [kellnerd/musicbrainz-bookmarklets#7]
Great work!
I love how you condensed the meat into regexp transformationRules.

What do you think about adding
* trimming of whitespace (leading, trailing, extra)
* replacing embedded bullets with middle dots (interpuncts)

?

**Comment by kellnerd** [comment]
I am not sure what you mean with trimming of whitespaces. MBS is already removing leading and trailing whitespaces from titles and collapses multiple whitespaces into one. Can you provide an example?

Do you come across [bullets](https://www.fileformat.info/info/unicode/char/2022/index.htm) quite often and if so, do they really need to be converted into [middle dots](https://www.fileformat.info/info/unicode/char/00b7/index.htm) in most cases? In the rare cases I encounter these I am never sure whether this is some kind of artist intent to have to them look more rounded 😇

**Comment by rtyle** [comment]
> MBS is already removing leading and trailing whitespaces from titles and collapses multiple whitespaces into one
If that is the case now then OK.
I know I have experienced otherwise but maybe it was for something else or the behavior has changed since.

> Do you come across bullets quite often
No
> do they really need to be converted into middle dots in most cases
Yes, IMO.
When I do see these, they are typically embedded as title / subtitle punctuation.
A bullet is not appropriate in such cases.
I don't recall ever considering a bullet as artist intent.
I think it is quite like ASCII vs. Unicode quotes.

Feel free to ignore this request.
I am thrilled with the way it is and am just struggling to offer improvements as support.
Thanks!

**Comment by kellnerd** [comment]
Thank you for your interest and the suggestion. Given that these bullets are rather rare and the existing transformation rules are all replacing ASCII with Unicode characters, I would prefer not to start adding rules to replace Unicode characters which are wrongly used.

At the moment I am using the search & replace function which is provided by @jesus2099's great [mb. SUPER MIND CONTROL Ⅱ X TURBO](https://github.com/jesus2099/konami-command/blob/master/mb_SUPER-MIND-CONTROL-II-X-TURBO.md#tracklist_tools) script to do this kind of replacement. Unfortunately it only remembers the last search expression so I am currently using a text file to store all the rules I need often.
But I already plan to create another userscript where you can add and store custom search & replace rules, group them into rulesets and run these sets on all kinds of input fields. I think this would be a better place for a bullet replacement rule.
